### ISSUE TITLE
Создать каркас приложения

### ISSUE THREAD

**Issue by Timurkazan99** [Timurkazan99/react-project#2]
Стек:
- React
- Redux
- TS
- Redux Thunk
- React Router
- React Router Dom
- Axios
- Redux Toolkit
- Sass
- Eslint

Страницы:
- **/** Главная страница
- **/search** Результаты поиска
- **/:id** Информация об 1-ом экземпляре
- **/signin** Страница авторизации
- **/signup** Страница регистрации
- **/favorites** Избранное
- **/history** История поиска

Workflow:
- Code linter

**Comment by Timurkazan99** [comment]
- Переименуй [my-app](https://github.com/Timurkazan99/react-project/tree/main/my-app) на frontend
- В my-app удали [README.md](https://github.com/Timurkazan99/react-project/blob/main/my-app/README.md) 
- Папку [app](https://github.com/Timurkazan99/react-project/tree/main/my-app/src/app) перекинь в папку [components](https://github.com/Timurkazan99/react-project/tree/main/my-app/src/components) 
- В [App.tsx](https://github.com/Timurkazan99/react-project/blob/main/my-app/src/app/App.tsx) вынеси <Routes>...</Routes> в отдельный компонент AppRouter
- Создай папку pages, и там создай для каждой страницы по файлу с пустым компонентом
- Создай папку utils/const.ts с url'ами роутов
- Создай файл routes.tsx с массивом { path, component }, где path это роут из const.ts, а component  это компонент из pages
- В [store](https://github.com/Timurkazan99/react-project/tree/main/my-app/src/store) создай папки `thunks и reducers`
- Из [features](https://github.com/Timurkazan99/react-project/tree/main/my-app/src/features) перенес slice в reducers, и удали папку features
- Добавь в [package.json](https://github.com/Timurkazan99/react-project/blob/main/my-app/package.json) скрипт `"linter": "npx eslint . --fix"`
- Добавь в корень проекта package.json, и там укажи
  ```
  "scripts": {
    "build": "npm run build --prefix frontend",
    "linter": "npm run linter --prefix frontend"
  },
  "workspaces": [
    "frontend"
  ],
  ```

**Comment by StaTov** [comment]
Работа выполнена. Commit: 0308f5a24b19027a20b1d26397b04bab58629b5b
