### ISSUE TITLE
Hotfix API

### ISSUE THREAD

**Issue by Timurkazan99** [Timurkazan99/react-project#24]
Исправить ошибки
![image](https://github.com/Timurkazan99/react-project/assets/43422137/2d3f9649-5eee-4c56-ac65-96d80728729e)
![image](https://github.com/Timurkazan99/react-project/assets/43422137/3f7e5d67-83e4-4e29-8560-b7a00c8f5ad5)

**Comment by DenisLatyshau** [comment]
fixed
